apiVersion: v1
name: ska-src-site-capabilities-api
description: A helm chart for ska-src-site-capabilities-api deployment
type: application
version: 0.3.49
appVersion: 0.3.49
maintainers:
  - name: Shraddha Bajare
    email: shraddha.bajare@skao.int