{{- if .Values.ing.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-core-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    io.kompose.service: core
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: {{ .Values.ing.api.host }}
    http:
      paths:
      - path: {{ .Values.svc.api.root_path }}(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: core
            port:
              number: {{ .Values.svc.api.containerPort }}
  ingressClassName: nginx
{{- end }}
