apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mongo
  name: {{ .Release.Name }}-mongo-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "mongo-svc-port"
    port: {{ .Values.svc.mongo.mongo_port }}
    targetPort: {{ .Values.svc.mongo.mongo_port }}
  selector:
    io.kompose.service: mongo
  type: LoadBalancer