{{- if not .Values.secrets.api.iam_client.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: iam-client-credentials
  namespace: {{ .Release.Namespace }}
data:
  client_id: {{ .Values.secrets.api.iam_client.id }}
  client_secret: {{ .Values.secrets.api.iam_client.secret }}
{{- end }}
---
{{- if not .Values.secrets.api.sessions.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: sessions-secret
  namespace: {{ .Release.Namespace }}
data:
  key: {{ .Values.secrets.api.sessions.key }}
{{- end }}
---
{{- if not .Values.secrets.common.mongo.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  namespace: {{ .Release.Namespace }}
data:
  password: {{ .Values.secrets.common.mongo.password }}
{{- end }}

