default:
  image: $SKA_K8S_TOOLS_BUILD_DEPLOY
  services:
    - docker:dind

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_DEPTH: 50

cache:
    paths:
        - build

stages:
    - lint
    - lint-post
    - build
    - test
    - publish
    - integration
    - pages
    - scan

join_lint_reports:
    stage: lint-post
    tags:
        - ${SKA_DEFAULT_RUNNER}
    script:
        - make join-lint-reports
    artifacts:
        paths:
            - build/
        when: always

# Standardised SKAO jobs (see https://gitlab.com/ska-telescope/templates-repository/-/blob/master/gitlab-ci/includes/)
include:
    # python formatting, linting and testing
    - project: "ska-telescope/templates-repository"
      file: "gitlab-ci/includes/python.gitlab-ci.yml"
    # docs
    - project: "ska-telescope/templates-repository"
      file: "gitlab-ci/includes/docs.gitlab-ci.yml"
    # OCI images build and publish
    - project: "ska-telescope/templates-repository"
      file: "gitlab-ci/includes/oci-image.gitlab-ci.yml"
    # helm chart linting and publishing
    - project: "ska-telescope/templates-repository"
      file: "gitlab-ci/includes/helm-chart.gitlab-ci.yml"
    # badges
    - project: "ska-telescope/templates-repository"
      file: "gitlab-ci/includes/finaliser.gitlab-ci.yml"
    # release automation
    - project: "ska-telescope/templates-repository"
      file: "gitlab-ci/includes/release.gitlab-ci.yml"
    # deployment stack integration tests
    - project: "ska-telescope/src/src-api/ska-src-api-deployment-stack"
      ref: main
      file: ".gitlab/ci/integration.yml"

integration:
  tags:
    - integration-testing
  variables:
    SERVICE_BRANCH: $CI_COMMIT_REF_NAME
    SERVICE_NAME: scapi
    TOOLKIT_IMAGE_NAME: registry.gitlab.com/ska-telescope/src/src-api/ska-src-api-deployment-stack/toolkit
    TOOLKIT_IMAGE_TAG: latest
    RUN_TESTS: "true"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_COMMIT_BRANCH'
      when: manual
      allow_failure: true

python-lint:
    image: registry.gitlab.com/ska-telescope/ska-cicd-k8s-tools/ska-cicd-k8s-tools-ubuntu24:0.0.1-dev.c24789cce
    before_script:
        - poetry config virtualenvs.in-project true
        - poetry install --no-interaction --no-ansi
    script:
        - make python-lint PYTHON_RUNNER="poetry run"

docs-build:
    image: registry.gitlab.com/ska-telescope/ska-cicd-k8s-tools/ska-cicd-k8s-tools-ubuntu24:0.0.1-dev.c24789cce

python-test:
    image: registry.gitlab.com/ska-telescope/ska-cicd-k8s-tools/ska-cicd-k8s-tools-ubuntu24:0.0.1-dev.c24789cce
    before_script:
        - poetry config virtualenvs.in-project true
        - poetry install --no-interaction --no-ansi
    script:
        - make python-test PYTHON_RUNNER="poetry run"

python-build-for-development:
    image: registry.gitlab.com/ska-telescope/ska-cicd-k8s-tools/ska-cicd-k8s-tools-ubuntu24:0.0.1-dev.c24789cce
    before_script:
        - poetry config virtualenvs.in-project true
        - poetry install --no-interaction --no-ansi
    script:
        - make python-build PYTHON_RUNNER="poetry run"
