version: 2
 
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.13"
  # apt_packages:
  # - plantuml # Add apt packages that you need present in the container here, for example plantuml
  jobs:
    post_create_environment:
      # Install uv
      # https://docs.astral.sh/uv/getting-started/installation/
      - pip install uv
    post_install:
      # Install the 'docs' dependency group into the RTD virtualenv
      # https://docs.readthedocs.com/platform/stable/build-customization.html#install-dependencies-with-uv
      - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --frozen --no-default-groups --group docs
 
sphinx:
  configuration: docs/src/conf.py
