version: "3.5"

services:
  scapi-mongo:
    container_name: scapi-mongo
    image: mongo:5.0.15
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

  scapi-core:
    container_name: scapi-core
    image: ska-src-site-capabilities-api-core:latest
    env_file:
      - .env
    environment:
      DISABLE_AUTHENTICATION: "no"
      API_ROOT_PATH:
      API_SCHEME: http
      IAM_CLIENT_CONF_URL: https://ska-iam.stfc.ac.uk/.well-known/openid-configuration
      API_IAM_CLIENT_ID: 1f901a38-955f-4198-aedb-002332a3c551
      API_IAM_CLIENT_SECRET:
      API_IAM_CLIENT_SCOPES: openid profile
      API_IAM_CLIENT_AUDIENCE: site-capabilities-api
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_HOST: scapi-mongo
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_PORT: 27017
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_INIT_DATA_RELPATH: etc/init
      PERMISSIONS_API_URL: https://permissions.srcnet.skao.int/api/v1
      PERMISSIONS_SERVICE_NAME: site-capabilities-api
      PERMISSIONS_SERVICE_VERSION: 1
      AUTH_API_URL: https://authn.srcnet.skao.int/api/v1
      SESSIONS_SECRET_KEY:
      SCHEMAS_RELPATH: ../../../etc/schemas
    depends_on:
      scapi-mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

