version: "3.5"

x-mongo-database: &mongo_database site-capabilities
x-mongo-root-username: &mongo_root_username root
x-mongo-root-password: &mongo_root_password ${MONGO_PASSWORD}

services:
  mongo:
    container_name: ska-src-site-capabilities-mongo
    image: mongo:5.0.15
    environment:
      MONGO_INITDB_DATABASE: *mongo_database
      MONGO_INITDB_ROOT_USERNAME: *mongo_root_username
      MONGO_INITDB_ROOT_PASSWORD: *mongo_root_password
    ports:
      - 27017:27017
  core:
    container_name: ska-src-site-capabilities-api-core
    image: ska-src-site-capabilities-api-core:latest
    build:
      context: .
      dockerfile: Dockerfile.core
    environment:
      DISABLE_AUTHENTICATION: "no"
      API_ROOT_PATH:
      API_SCHEME: http
      IAM_CLIENT_CONF_URL: https://ska-iam.stfc.ac.uk/.well-known/openid-configuration
      API_IAM_CLIENT_ID: 1f901a38-955f-4198-aedb-002332a3c551
      API_IAM_CLIENT_SECRET:
      API_IAM_CLIENT_SCOPES: openid profile
      API_IAM_CLIENT_AUDIENCE: site-capabilities-api
      MONGO_DATABASE: *mongo_database
      MONGO_HOST: ska-src-site-capabilities-mongo
      MONGO_PASSWORD:
      MONGO_PORT: 27017
      MONGO_USERNAME: *mongo_root_username
      MONGO_INIT_DATA_RELPATH: etc/init
      PERMISSIONS_API_URL: https://permissions.srcdev.skao.int/api/v1
      PERMISSIONS_SERVICE_NAME: site-capabilities-api
      PERMISSIONS_SERVICE_VERSION: 1
      AUTH_API_URL: https://authn.srcdev.skao.int/api/v1
      SESSIONS_SECRET_KEY:
      SCHEMAS_RELPATH: ../../../etc/schemas
    ports:
      - 8080:8080
