version: "3.5"
services:
  mongo:
    container_name: ska-src-site-capabilities-mongo
    image: mongo:5.0.15
    environment:
      MONGO_INITDB_DATABASE: site-capabilities
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
  core:
    container_name: ska-src-site-capabilities-core
    image: ska-src-site-capabilities-core:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      API_PREFIX: http
      API_HOST: localhost
      API_PORT: 8080
      IAM_CLIENT_CONF_URL: https://ska-iam.stfc.ac.uk/.well-known/openid-configuration
      IAM_CLIENT_NAME: ska
      IAM_CLIENT_SCOPES: openid email profile
      MONGO_DATABASE: site-capabilities
      MONGO_HOST: ska-src-site-capabilities-mongo
      MONGO_PASSWORD: secret
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      SCHEMAS_RELPATH: ../../../etc/schemas
      SESSION_MIDDLEWARE_SECRET_KEY: $SESSION_MIDDLEWARE_SECRET_KEY
      SKA_CLIENT_ID: $SKA_CLIENT_ID
      SKA_CLIENT_SECRET: $SKA_CLIENT_SECRET
    ports:
      - 8080:8080
