version: "3.5"
services:
  mongo:
    container_name: ska-src-site-capabilities-mongo
    image: mongo:5.0.15
    environment:
      MONGO_INITDB_DATABASE: site-capabilities
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
  core:
    container_name: ska-src-site-capabilities-core
    image: ska-src-site-capabilities-core:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DISABLE_AUTHENTICATION: "no"
      API_ROOT_PATH:
      IAM_CLIENT_CONF_URL: https://ska-iam.stfc.ac.uk/.well-known/openid-configuration
      API_IAM_CLIENT_ID: 1f901a38-955f-4198-aedb-002332a3c551
      API_IAM_CLIENT_SECRET:
      API_IAM_CLIENT_SCOPES: openid profile
      API_IAM_CLIENT_AUDIENCE: site-capabilities-api
      MONGO_DATABASE: site-capabilities
      MONGO_HOST: ska-src-site-capabilities-mongo
      MONGO_PASSWORD: secret
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      PERMISSIONS_API_URL: https://permissions.srcdev.skao.int/api/v1
      PERMISSIONS_SERVICE_NAME: site-capabilities-api
      PERMISSIONS_SERVICE_VERSION: 1
      SCHEMAS_RELPATH: ../../../etc/schemas
    ports:
      - 8080:8080
