apiVersion: v2
name: scapi
description: A helm chart for scapi deployment
type: application
version: 0.3.91
appVersion: 0.3.91
maintainers:
    - name: Rob Barnsley
      email: rob.barnsley@skao.int
    - name: Michele Delli Veneri
      email: michele.delliveneri@skao.int
