global:
    minikube: true
    retry:
        - "--tries=10"
        - "--sleep=5"

labels:
    app: scapi

annotations:
    app.gitlab.com/app: CI_PROJECT_PATH_SLUG

svc:
    api:
        image:
            registry: artefact.skao.int
            image: scapi-core
            tag: 0.3.95
            pullPolicy: Always
        root_path: /api
        scheme: https
        iam_client_conf_url: https://ska-iam.stfc.ac.uk/.well-known/openid-configuration
        iam_client_scopes: "openid profile"
        iam_client_audience: site-capabilities-api
        mongo_host: mongo
        mongo_port: 27017
        mongo_init_data_relpath: etc/init
        permissions_api_url: https://permissions.srcnet.skao.int/api/v1
        permissions_service_name: site-capabilities-api
        permissions_service_version: 1
        auth_api_url: https://authn.srcnet.skao.int/api/v1
        sessions_secret_key:
        schemas_relpath: ../../../etc/schemas
        uvicorn_nworkers: 4
        uvicorn_reload: "false"
    common:
        mongo_database: site-capabilities
        mongo_username: root

secrets:
    api:
        iam_client:
            id: ""
            secret: ""
            # If existingSecret is defined and set to true, the above attributes will be ignored in favour of the data
            # contained in an existing secret, "iam-client-credentials".
            existingSecret: false
        sessions:
            key: ""
            # If existingSecret is defined and set to true, the above attributes will be ignored in favour of the data
            # contained in an existing secret, "sessions-secret".
            existingSecret: false
    common:
        mongo:
            password: ""
            # If existingSecret is defined and set to true, the above attributes will be ignored in favour of the data
            # contained in an existing secret, "mongo-credentials".
            existingSecret: false

observability:
    log:
        level: INFO
        format: json
        app_name: scapi
        enable_redaction: "true"
    otel:
        service_name: scapi
        traces_enabled: "true"
        metrics_enabled: "true"
        logs_enabled: "true"
        exporter_otlp_endpoint: "http://monitoring-opentelemetry-collector.monitoring.svc.cluster.local:4317"
        resource_attributes: "service.namespace=ska-src"

ing:
    enabled: true
    api:
        host: site-capabilities.srcnet.skao.int

persistence:
    storageClass: bds1
    existingClaim: ""
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
