apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: core-ingress
  namespace: {{ .Release.Namespace }}
  label:
    app: core
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /{{ .Release.Namespace }}/alarm-configurator/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: core
            port:
              number: 8080
  ingressClassName: nginx
