apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: core-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: {{ .Values.ing.api.host }}
    http:
      paths:
      - path: {{ .Values.svc.api.root_path }}(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: core
            port:
              number: 8080
  ingressClassName: nginx
