apiVersion: v1
kind: Service
metadata:
  name: core
  namespace: {{ .Release.Namespace }}
  labels:
    io.kompose.service: core
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    io.kompose.service: core
  type: LoadBalancer